"""
Gemini AI service for generating market analysis reports
"""
import json
import logging
from datetime import datetime
from typing import Dict, List

import httpx

from app.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()

GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"


REPORT_PROMPT_TEMPLATE = """You are an expert trade analyst specializing in Indian market sectors.
Analyze the following sector and market data, then generate a comprehensive trade opportunities report.

SECTOR: {sector}
DATE: {date}

MARKET DATA & NEWS COLLECTED:
{market_data}

Generate a detailed markdown report with the following structure. Be specific, data-driven, and actionable.
Focus on India's trade landscape, regulatory environment, and practical opportunities.

---

# 🏭 Trade Opportunities Report: {sector_title} Sector
**Analysis Date:** {date}
**Market:** India

---

## 📊 Executive Summary
[3-4 sentences summarizing the key findings and top opportunities]

---

## 🌍 Sector Overview
### Current Market Position
[India's current position in global {sector} trade - size, rank, growth rate]

### Key Market Indicators
- **Market Size:** [estimated value]
- **YoY Growth Rate:** [percentage]
- **Export Value (Latest):** [value]
- **Import Value (Latest):** [value]
- **Key Trade Partners:** [top 3-5 countries]

---

## 📈 Trade Opportunities

### 🟢 High-Priority Export Opportunities
[List 3-5 specific export opportunities with target markets and rationale]

### 🔵 Import Substitution Opportunities
[List 2-3 areas where India can reduce imports through domestic production]

### 🟡 Emerging Opportunities
[List 2-3 emerging/future opportunities based on trends]

---

## ⚠️ Challenges & Risk Factors
[List 4-5 key challenges with brief explanations]

---

## 🏛️ Government Policies & Schemes
[List relevant schemes, PLI benefits, FTAs, or policies supporting this sector]

---

## 🏢 Key Players & Competitive Landscape
### Top Indian Companies
[List 4-6 major Indian players]

### International Competition
[Key international competitors India faces]

---

## 💡 Strategic Recommendations

### For Exporters
1. [Specific recommendation]
2. [Specific recommendation]
3. [Specific recommendation]

### For Importers/Buyers
1. [Specific recommendation]
2. [Specific recommendation]

### For Investors
1. [Specific recommendation]
2. [Specific recommendation]

---

## 📅 Outlook & Forecast
[6-12 month outlook for the sector with specific predictions]

---

## 📚 Data Sources & References
[List the sources used in this analysis]

---
*Report generated by Trade Opportunities API | Data as of {date}*
*Note: This report is AI-generated for informational purposes. Verify critical data before making business decisions.*
"""


class GeminiService:
    def __init__(self):
        self.api_key = settings.gemini_api_key
        self.timeout = httpx.Timeout(60.0)

    async def generate_analysis(self, sector: str, search_data: Dict) -> str:
        """Generate market analysis report using Gemini"""

        if not self.api_key:
            logger.warning("No Gemini API key configured, using fallback report")
            return self._generate_fallback_report(sector, search_data)

        # Format search results for the prompt
        market_data = self._format_search_data(search_data)

        prompt = REPORT_PROMPT_TEMPLATE.format(
            sector=sector,
            sector_title=sector.replace("-", " ").title(),
            date=datetime.utcnow().strftime("%B %d, %Y"),
            market_data=market_data
        )

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.post(
                    f"{GEMINI_URL}?key={self.api_key}",
                    json={
                        "contents": [{"parts": [{"text": prompt}]}],
                        "generationConfig": {
                            "temperature": 0.7,
                            "topK": 40,
                            "topP": 0.95,
                            "maxOutputTokens": 4096,
                        },
                        "safetySettings": [
                            {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
                            {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
                        ]
                    }
                )
                response.raise_for_status()
                data = response.json()

                # Extract text from response
                candidates = data.get("candidates", [])
                if candidates:
                    content = candidates[0].get("content", {})
                    parts = content.get("parts", [])
                    if parts:
                        report = parts[0].get("text", "")
                        if report:
                            logger.info(f"Successfully generated Gemini report for {sector}")
                            return report

                raise ValueError("Empty response from Gemini API")

        except httpx.HTTPStatusError as e:
            logger.error(f"Gemini API HTTP error: {e.response.status_code} - {e.response.text}")
            if e.response.status_code == 400:
                raise ValueError(f"Invalid request to Gemini API: {e.response.text}")
            elif e.response.status_code == 403:
                raise ValueError("Invalid or missing Gemini API key")
            elif e.response.status_code == 429:
                raise ValueError("Gemini API rate limit exceeded. Please try again later.")
            return self._generate_fallback_report(sector, search_data)

        except Exception as e:
            logger.error(f"Gemini API error: {e}")
            return self._generate_fallback_report(sector, search_data)

    def _format_search_data(self, search_data: Dict) -> str:
        """Format search results for the prompt"""
        results = search_data.get("results", [])
        if not results:
            return "No real-time data available. Please rely on your training knowledge for analysis."

        formatted = []
        for i, r in enumerate(results[:15], 1):
            title = r.get("title", "No title")
            snippet = r.get("snippet", "No description")
            url = r.get("url", "")
            formatted.append(f"{i}. **{title}**\n   {snippet}\n   Source: {url}")

        return "\n\n".join(formatted)

    def _generate_fallback_report(self, sector: str, search_data: Dict) -> str:
        """Fallback report when Gemini API is unavailable"""
        sector_title = sector.replace("-", " ").title()
        date = datetime.utcnow().strftime("%B %d, %Y")
        results = search_data.get("results", [])

        sources_section = ""
        if results:
            sources = "\n".join([f"- {r.get('title', 'Unknown')} - {r.get('url', '')}" for r in results[:5]])
            sources_section = f"\n## 📚 Data Sources\n{sources}"

        return f"""# 🏭 Trade Opportunities Report: {sector_title} Sector
**Analysis Date:** {date}
**Market:** India

> ⚠️ **Note:** This is a template report. Configure your `GEMINI_API_KEY` in `.env` for AI-powered analysis.

---

## 📊 Executive Summary

The {sector_title} sector in India presents significant trade opportunities driven by domestic demand growth,
government policy support, and India's growing role in global supply chains. This report outlines key
areas for trade exploration based on available market data.

---

## 🌍 Sector Overview

India's {sector_title} sector is a significant contributor to the national economy. The sector has seen
consistent growth driven by policy initiatives, FDI inflows, and technological adoption.

### Key Market Indicators
- **Market Stage:** Growing
- **Policy Support:** Active government schemes and PLI benefits
- **Trade Balance:** To be verified with live data
- **Key Trade Partners:** USA, UAE, China, EU, ASEAN

---

## 📈 Trade Opportunities

### 🟢 Export Opportunities
1. **Value-Added Products** - Move up the value chain from raw materials to finished goods
2. **Niche/Specialty Markets** - Target premium segments in developed markets
3. **South-South Trade** - Leverage ASEAN, Africa, Latin America opportunities

### 🔵 Import Substitution
1. **Technology & Machinery** - Develop domestic manufacturing under Atmanirbhar Bharat
2. **Raw Material Processing** - Build processing capacity for key inputs

### 🟡 Emerging Opportunities
1. **Digital Integration** - Technology-enabled trade facilitation
2. **Sustainability Play** - Green/ESG-compliant supply chains attracting premium buyers

---

## ⚠️ Key Challenges
- Global price volatility impacting margins
- Infrastructure bottlenecks in logistics
- Regulatory compliance complexity in target markets
- Competition from established exporters
- Technology adoption lag in SME segments

---

## 🏛️ Government Schemes
- **PLI Scheme** - Production Linked Incentive for domestic manufacturing
- **MEIS/RoDTEP** - Export incentive schemes
- **FTAs** - Free Trade Agreements with key partners
- **SEZ/EOU** - Special Economic Zones and Export Oriented Units

---

## 💡 Strategic Recommendations

### For Exporters
1. Leverage government export promotion schemes and PLI benefits
2. Invest in quality certifications for target market compliance
3. Diversify market presence beyond traditional trading partners

### For Investors
1. Focus on capacity expansion in high-growth sub-segments
2. Explore technology partnerships with global leaders
3. Build ESG-compliant operations for premium market access

---

## 📅 Outlook
The {sector_title} sector outlook for 2024-25 remains positive, supported by domestic consumption growth,
government policy push, and India's positioning as a global manufacturing alternative.

{sources_section}

---
*Report generated by Trade Opportunities API | {date}*
*Configure GEMINI_API_KEY for AI-powered analysis with real-time insights.*
"""


# Service instance
gemini_service = GeminiService()